### ISSUE TITLE
tool/upgrade_by_passwd.py does not work with python3

### ISSUE THREAD

**Issue by lanodan** [Nitrokey/nitrokey-start-firmware#16]
```
…/nitrokey-start-firmware/tool $ python3.6 ./upgrade_by_passwd.py ../prebuilt/$RTM/regnual.bin ../prebuilt/$RTM/gnuk.bin
  File "./upgrade_by_passwd.py", line 40
    print "CRC32: %04x\n" % crc32code
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("CRC32: %04x\n" % crc32code)?
```

Python 2 will be EOL in 2020-01-01 please move to Python 3.

**Comment by szszszsz** [comment]
Fixed for `upgrade_by_passwd.py` with https://github.com/Nitrokey/nitrokey-start-firmware/commit/57363dd211ff12fd1be19387f01bf653d7549e99. The error came from using the old branch, which was default for some time.
Other tools are rewritten in the latest upstream. This ticket will be closed once changes will be merged (planned on the next release).
