### ISSUE TITLE
Idea: multiple identities

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-start-firmware#27]
Provide a way to simulate multiple OpenPGP 2.x cards on the device.
Could be a workaround for #22.

cc @alex-nitrokey 

- [x] Write test cases (test ID change multiple times to check the counter in action, check actual key changes, check certDO limit for the last identity).
- [x] Test by hand (PIN cache between changes).

**Comment by szszszsz** [comment]
Mentioned commit triples the user storage, leaving 3kB for firmware changes.

**Comment by alex-nitrokey** [comment]
Mh, I would say the best approach would be to support and implement the MANAGE SECURITY ENVIRONMENT (MSE) feature of [OpenPGP Card v3.3 specification](https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.3.1.pdf). This way, OpenSC would just work as in *real* OpenPGP Cards. I am not sure if the approach above would work in OpenSC, but I guess it could get really messy.

In the end it can get more and more difficult to get Gnu/Start devices supported by software if they do not stick to the specification imho. So best case would be to support *all* changes of OpenPGP Card v3.3 or none.

Having admin-less PIN usage and ECC independent of any specification has already caused some problems, although these are desirable features.

**Comment by szszszsz** [comment]
Merged to main branch with #33. To be tested.
