### ISSUE TITLE
ACK button for signatures

### ISSUE THREAD

**Issue by fgervais** [Nitrokey/nitrokey-start-firmware#57]
It seems that ACKBTN support is enabled by default since RTM.7:

https://github.com/Nitrokey/nitrokey-start-firmware/commit/6c721472483cf1b173b4ea92367ef9387ea42448

I have RTM.10 on mine and it's not asking to touch, for signatures at least. Is there something I need to do to enable it?

**Comment by jans23** [comment]
There is no physical (touch) button in Nitrokey Start (yet). We will add such physical touch button sooner or later. Potentially this will come with a re-implementation of the firmware. However, no specific plan or roadmap yet. We will tackle this after the upcoming Nitrokey FIDO2 NFC release.

**Comment by fgervais** [comment]
Oh but I looked at the kicad files and I see a big touch pad bottom side (pcb botton, key top).

Am I looking at a future revision or something?

**Comment by fgervais** [comment]
![image](https://user-images.githubusercontent.com/5411996/93889137-d837bb80-fcb6-11ea-8750-722f08754e14.png)

**Comment by jans23** [comment]
Yes, the hardware layout you are looking at is not what is shipped as NK Start. The correct hardware layout is in Repo nitrokey-pro-hardware.

22.09.2020 15:26:29 Francois Gervais <notifications@github.com>:

**Comment by fgervais** [comment]
This is the nitrokey start?

![image](https://user-images.githubusercontent.com/5411996/93890508-63658100-fcb8-11ea-9df9-e48cd4b8867f.png)

**Comment by jans23** [comment]
The hardware repository is [this](https://github.com/Nitrokey/nitrokey-pro-hardware/) and [here](https://github.com/Nitrokey/nitrokey-pro-firmware/) are pictures.
