### ISSUE TITLE
Nitrokey Start listed as none

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-start-firmware#68]
Nitrokey Start is listed as 
> none: none none (none)

Command: `$ nitropy list`

OS: Windows, Linux
To investigate and correct.

Connected:
- Nitrokey/pynitrokey#27
- https://support.nitrokey.com/t/nitrokey-start-gelistet-als-none-none-none-none/4044

**Comment by nitro-rico** [comment]
```
Command line tool to interact with Nitrokey devices 0.4.21
:: 'Nitrokey FIDO2' keys
:: 'Nitrokey Start' keys:
FSIJ-1.2.15-34353135: Nitrokey Nitrokey Start (RTM.12)
:: 'Nitrokey 3' keys
```
works with following components:
```
Driver=usbfs

scdaemon/focal-updates 2.2.19-3ubuntu2.1 amd64 
gnupg2 (2.2.19-3ubuntu2.1)

Linux 5.13.0-40-generic Nitrokey/pynitrokey#45~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by szszszsz** [comment]
Works on our side. To check, if this could be caused by the firmware update process somehow.

**Comment by szszszsz** [comment]
Looks like this is sourced rather in the Nitrokey Start firmware / this given device flashing setup, than in pynitrokey.

Nothing to do on this side. Leaving open for monitoring, and gathering similar reports in the future.

**Comment by szszszsz** [comment]
Was not reported again. Closing.
